# Generated by Django 2.1.4 on 2018-12-29 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField()),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateTimeField()),
                ('path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField()),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField()),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateTimeField()),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('shoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Shoot')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='shoot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Shoot'),
        ),
    ]
