# Generated by Django 2.1.4 on 2018-12-30 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181229_0506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-updatedAt',)},
        ),
        migrations.AlterModelOptions(
            name='shoot',
            options={'ordering': ('-updatedAt',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-updatedAt',)},
        ),
        migrations.RemoveField(
            model_name='image',
            name='shoot',
        ),
        migrations.AddField(
            model_name='image',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
