# Generated by Django 2.1.4 on 2018-12-31 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181230_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('companyName', models.CharField(max_length=200)),
                ('logoUrl', models.URLField()),
                ('watermarkUrl', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
