# Generated by Django 2.1.4 on 2018-12-31 20:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logoUrl',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='watermarkUrl',
        ),
        migrations.AddField(
            model_name='brand',
            name='logoFile',
            field=models.FileField(blank=True, null=True, upload_to=app.models.logo_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='watermarkFile',
            field=models.FileField(blank=True, null=True, upload_to=app.models.watermark_path),
        ),
    ]
